### ISSUE TITLE
Kali and Ubuntu Installation issues - requirements.txt

### ISSUE THREAD

**Issue by r1cs3c** [MircoT/flask-soap-server#1]
Hello,

I just wanted to let you know that we had issues doing the requirements.txt installation step `pip install -r requirements.txt` as the distribute and lxml required versions did not install, they kept giving us an error. To fix we simply took the version off and the server dependencies installed properly. The modified requirements.txt file contents look like:

Flask==0.9
Flask-Enterprise==1.0
Jinja2==2.6
Werkzeug==0.8.3
argparse==1.2.1
distribute
honcho==0.3.1
lxml
pytz==2013b
soaplib==2.0.0-beta2
suds==0.4
wsgiref==0.1.2

Cheers,

Ric

**Comment by MircoT** [comment]
Thank you, I updated the requirements. But I think it would be better to convert this example to the new library for rpc like [spyne.io](http://spyne.io/)
